<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceImage;
use Illuminate\Database\Seeder;

class AdditionalServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'freelancer_name' => 'Aurel Maharani',
                'service_name' => 'Fotografer Wisuda Premium Outdoor',
                'category' => 'Fotografi',
                'price' => 450000,
                'location' => 'Jakarta',
                'description' => '<p>Saya menyediakan jasa <strong>fotografi wisuda premium</strong> dengan konsep outdoor yang natural, cerah, dan elegan. Cocok untuk mahasiswa yang ingin mengabadikan momen kelulusan dengan hasil foto yang <em>clean</em>, modern, dan siap diunggah ke media sosial.</p><ol><li>Foto individu dan keluarga.</li><li>Editing warna profesional.</li><li>File digital resolusi tinggi.</li></ol>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Fotografi, Editing Foto, Outdoor Photoshoot',
                'whatsapp' => '081210010001',
                'email' => 'aurel@example.com',
            ],
            [
                'freelancer_name' => 'Rangga Pradipta',
                'service_name' => 'Fotografer Produk Fashion dan UMKM',
                'category' => 'Fotografi',
                'price' => 350000,
                'location' => 'Bandung',
                'description' => '<p>Jasa foto produk untuk kebutuhan <strong>catalogue, marketplace, dan promosi Instagram</strong>. Saya membantu menampilkan produk agar terlihat lebih profesional, menarik, dan memiliki nilai jual yang kuat.</p><p>Setiap sesi foto memperhatikan <em>lighting</em>, komposisi, detail produk, serta gaya visual sesuai identitas brand.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Product Photography, Lighting, Photo Retouching',
                'whatsapp' => '081210010002',
                'email' => 'rangga@example.com',
            ],
            [
                'freelancer_name' => 'Nesya Rahmadani',
                'service_name' => 'Dokumentasi Event Seminar dan Workshop',
                'category' => 'Fotografi',
                'price' => 500000,
                'location' => 'Surabaya',
                'description' => '<p>Menerima dokumentasi acara seminar, workshop, gathering, dan kegiatan kampus. Hasil dokumentasi dibuat dengan gaya <strong>rapi, natural, dan profesional</strong>.</p><ul><li>Foto suasana acara.</li><li>Foto pembicara dan peserta.</li><li>Dokumentasi detail kegiatan.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Event Photography, Candid Photo, Editing',
                'whatsapp' => '081210010003',
                'email' => 'nesya@example.com',
            ],
            [
                'freelancer_name' => 'Ilham Saputra',
                'service_name' => 'Desain Logo Brand Minimalis',
                'category' => 'Desain Grafis',
                'price' => 300000,
                'location' => 'Medan',
                'description' => '<p>Saya membantu membuat <strong>logo brand minimalis</strong> yang profesional, mudah dikenali, dan sesuai karakter bisnis. Desain dibuat tidak hanya menarik secara visual, tetapi juga memiliki konsep yang jelas.</p><ol><li>Konsultasi konsep brand.</li><li>Alternatif desain logo.</li><li>File final siap pakai.</li></ol>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Logo Design, Branding, Adobe Illustrator',
                'whatsapp' => '081210010004',
                'email' => 'ilham@example.com',
            ],
            [
                'freelancer_name' => 'Dhea Anindya',
                'service_name' => 'Desain Feed Instagram Estetik',
                'category' => 'Desain Grafis',
                'price' => 250000,
                'location' => 'Bekasi',
                'description' => '<p>Jasa desain feed Instagram untuk bisnis, personal branding, dan komunitas. Desain dibuat dengan tampilan <em>aesthetic</em>, konsisten, dan sesuai warna identitas brand.</p><p>Paket ini cocok untuk Anda yang ingin tampilan media sosial lebih <strong>rapi, profesional, dan mudah menarik perhatian audiens</strong>.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Canva, Social Media Design, Content Layout',
                'whatsapp' => '081210010005',
                'email' => 'dhea@example.com',
            ],
            [
                'freelancer_name' => 'Fahri Maulana',
                'service_name' => 'Desain Poster Event dan Promosi',
                'category' => 'Desain Grafis',
                'price' => 180000,
                'location' => 'Semarang',
                'description' => '<p>Menyediakan jasa desain poster untuk event, promosi produk, seminar, lomba, dan kebutuhan publikasi digital. Desain dibuat <strong>informatif, menarik, dan mudah dibaca</strong>.</p><ul><li>Poster Instagram.</li><li>Flyer digital.</li><li>Banner promosi.</li></ul>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Poster Design, Canva, Photoshop',
                'whatsapp' => '081210010006',
                'email' => 'fahri@example.com',
            ],
            [
                'freelancer_name' => 'Viona Permata',
                'service_name' => 'Editing Video Reels dan TikTok',
                'category' => 'Video Editing',
                'price' => 175000,
                'location' => 'Palembang',
                'description' => '<p>Saya menyediakan jasa editing video pendek untuk Reels, TikTok, dan YouTube Shorts. Video dibuat dengan alur cepat, transisi halus, subtitle rapi, dan gaya visual yang <em>engaging</em>.</p><ol><li>Cutting video.</li><li>Subtitle otomatis/manual.</li><li>Efek dan transisi sesuai kebutuhan.</li></ol>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'CapCut, Premiere Pro, Subtitle, Short Video',
                'whatsapp' => '081210010007',
                'email' => 'viona@example.com',
            ],
            [
                'freelancer_name' => 'Arman Yusuf',
                'service_name' => 'Editing Video Aftermovie Event',
                'category' => 'Video Editing',
                'price' => 550000,
                'location' => 'Jakarta',
                'description' => '<p>Jasa editing video aftermovie untuk seminar, konser kecil, gathering, dan acara komunitas. Hasil video dibuat dengan nuansa <strong>cinematic</strong>, musik yang sesuai, dan alur cerita yang menarik.</p><p>Saya juga menyesuaikan warna video agar terlihat lebih <em>professional</em>.</p>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Premiere Pro, Color Grading, Cinematic Editing',
                'whatsapp' => '081210010008',
                'email' => 'arman@example.com',
            ],
            [
                'freelancer_name' => 'Sabila Putri',
                'service_name' => 'Editing Video Promosi Produk',
                'category' => 'Video Editing',
                'price' => 300000,
                'location' => 'Bandung',
                'description' => '<p>Membantu membuat video promosi produk yang singkat, jelas, dan menarik. Cocok untuk kebutuhan <strong>iklan media sosial, katalog digital, dan campaign UMKM</strong>.</p><ul><li>Tambahan teks promosi.</li><li>Transisi modern.</li><li>Format siap upload.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Video Ads, Motion Text, Product Video',
                'whatsapp' => '081210010009',
                'email' => 'sabila@example.com',
            ],
            [
                'freelancer_name' => 'Galih Prakoso',
                'service_name' => 'Voice Over Iklan dan Company Profile',
                'category' => 'Musik & Audio',
                'price' => 200000,
                'location' => 'Surabaya',
                'description' => '<p>Jasa <strong>voice over</strong> untuk iklan, company profile, video pembelajaran, dan konten digital. Karakter suara dapat disesuaikan, mulai dari formal, ramah, energik, hingga naratif.</p><p>Audio akan diproses agar terdengar lebih bersih dan nyaman didengar.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Voice Over, Dubbing, Audio Recording',
                'whatsapp' => '081210010010',
                'email' => 'galih@example.com',
            ],
            [
                'freelancer_name' => 'Meisya Lestari',
                'service_name' => 'Mixing dan Mastering Podcast',
                'category' => 'Musik & Audio',
                'price' => 250000,
                'location' => 'Bekasi',
                'description' => '<p>Mengolah audio podcast agar terdengar lebih jernih, stabil, dan profesional. Saya akan membantu mengurangi noise, merapikan volume, serta membuat hasil akhir lebih nyaman didengar.</p><ol><li>Noise reduction.</li><li>Leveling suara.</li><li>Mastering final audio.</li></ol>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Audio Editing, Mixing, Mastering',
                'whatsapp' => '081210010011',
                'email' => 'meisya@example.com',
            ],
            [
                'freelancer_name' => 'Rayhan Aditya',
                'service_name' => 'Pembuatan Jingle Brand Pendek',
                'category' => 'Musik & Audio',
                'price' => 450000,
                'location' => 'Semarang',
                'description' => '<p>Saya membuat jingle pendek untuk brand, iklan, podcast, dan konten promosi. Jingle dibuat dengan konsep yang <strong>mudah diingat</strong>, enak didengar, dan sesuai karakter produk.</p><p>Cocok untuk UMKM yang ingin meningkatkan identitas audio brand.</p>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Jingle, Music Production, Audio Arrangement',
                'whatsapp' => '081210010012',
                'email' => 'rayhan@example.com',
            ],
            [
                'freelancer_name' => 'Kirania Putri',
                'service_name' => 'MC Seminar dan Acara Formal',
                'category' => 'MC & Event',
                'price' => 400000,
                'location' => 'Palembang',
                'description' => '<p>Menerima jasa MC untuk seminar, workshop, talkshow, dan acara formal. Pembawaan acara dilakukan secara <strong>terstruktur, komunikatif, dan profesional</strong>.</p><ul><li>Menyusun alur komunikasi acara.</li><li>Membantu menjaga ritme acara.</li><li>Menyesuaikan gaya bahasa dengan audiens.</li></ul>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Public Speaking, MC Formal, Event Handling',
                'whatsapp' => '081210010013',
                'email' => 'kirania@example.com',
            ],
            [
                'freelancer_name' => 'Bima Wardhana',
                'service_name' => 'MC Wedding dan Engagement',
                'category' => 'MC & Event',
                'price' => 700000,
                'location' => 'Jakarta',
                'description' => '<p>Jasa MC untuk wedding, engagement, dan acara keluarga. Saya membawakan acara dengan gaya yang hangat, rapi, dan tetap elegan.</p><p>Fokus utama saya adalah menjaga suasana acara tetap <em>flowing</em>, nyaman, dan sesuai rundown.</p>',
                'work_experience' => '6 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'MC Wedding, Rundown, Public Speaking',
                'whatsapp' => '081210010014',
                'email' => 'bima@example.com',
            ],
            [
                'freelancer_name' => 'Tania Febrianti',
                'service_name' => 'Event Planner Mini Gathering',
                'category' => 'MC & Event',
                'price' => 500000,
                'location' => 'Bandung',
                'description' => '<p>Membantu merancang acara kecil seperti gathering, ulang tahun, launching produk, dan acara komunitas. Saya membantu menyusun konsep acara agar lebih <strong>rapi, menarik, dan mudah dijalankan</strong>.</p><ol><li>Konsep acara.</li><li>Rundown.</li><li>Koordinasi kebutuhan acara.</li></ol>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Event Planning, Rundown, Coordination',
                'whatsapp' => '081210010015',
                'email' => 'tania@example.com',
            ],
            [
                'freelancer_name' => 'Putra Mahendra',
                'service_name' => 'Penulisan Artikel SEO Website',
                'category' => 'Penulisan',
                'price' => 150000,
                'location' => 'Surabaya',
                'description' => '<p>Menyediakan jasa penulisan artikel SEO untuk blog, website bisnis, dan media digital. Artikel ditulis dengan struktur yang jelas, gaya bahasa natural, serta memperhatikan <strong>keyword</strong> dan kenyamanan pembaca.</p><ul><li>Judul menarik.</li><li>Subjudul rapi.</li><li>Konten informatif dan original.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'SEO Writing, Blog Writing, Content Writing',
                'whatsapp' => '081210010016',
                'email' => 'putra@example.com',
            ],
            [
                'freelancer_name' => 'Aisyah Nurlaila',
                'service_name' => 'Copywriting Produk dan Caption Iklan',
                'category' => 'Penulisan',
                'price' => 175000,
                'location' => 'Bekasi',
                'description' => '<p>Saya membantu membuat copywriting untuk caption produk, iklan, katalog, dan landing page. Tulisan dibuat <strong>persuasif</strong>, tidak kaku, dan sesuai dengan target pasar.</p><p>Cocok untuk brand yang ingin meningkatkan kualitas komunikasi promosi.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Copywriting, Caption, Product Description',
                'whatsapp' => '081210010017',
                'email' => 'aisyah@example.com',
            ],
            [
                'freelancer_name' => 'Darren Putranto',
                'service_name' => 'Penulisan CV dan Profil LinkedIn',
                'category' => 'Penulisan',
                'price' => 250000,
                'location' => 'Medan',
                'description' => '<p>Membantu menyusun CV, surat lamaran, dan profil LinkedIn agar lebih profesional. Penulisan berfokus pada pencapaian, pengalaman, serta keunggulan kandidat.</p><ol><li>Review data pengalaman.</li><li>Perbaikan struktur CV.</li><li>Optimasi kalimat profesional.</li></ol>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'CV Writing, Career Profile, LinkedIn Optimization',
                'whatsapp' => '081210010018',
                'email' => 'darren@example.com',
            ],
            [
                'freelancer_name' => 'Kevin Hidayat',
                'service_name' => 'Pembuatan Website Company Profile',
                'category' => 'Website & Programming',
                'price' => 1500000,
                'location' => 'Semarang',
                'description' => '<p>Saya membuat website company profile yang modern, responsif, dan mudah digunakan. Website dirancang untuk memperkenalkan bisnis, layanan, portofolio, serta kontak perusahaan secara profesional.</p><ul><li>Desain responsif.</li><li>Halaman profil bisnis.</li><li>Integrasi tombol kontak.</li></ul>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Laravel, HTML, Tailwind CSS, MySQL',
                'whatsapp' => '081210010019',
                'email' => 'kevin@example.com',
            ],
            [
                'freelancer_name' => 'Mira Anggraeni',
                'service_name' => 'Landing Page Produk UMKM',
                'category' => 'Website & Programming',
                'price' => 900000,
                'location' => 'Palembang',
                'description' => '<p>Jasa pembuatan landing page untuk promosi produk, jasa, dan campaign digital. Tampilan dibuat <strong>menarik, cepat dipahami, dan fokus pada konversi</strong>.</p><p>Landing page cocok untuk UMKM yang ingin terlihat lebih profesional secara online.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Landing Page, UI Design, Tailwind CSS',
                'whatsapp' => '081210010020',
                'email' => 'mira@example.com',
            ],
            [
                'freelancer_name' => 'Alvin Firmansyah',
                'service_name' => 'Perbaikan Bug Website Laravel',
                'category' => 'Website & Programming',
                'price' => 350000,
                'location' => 'Jakarta',
                'description' => '<p>Membantu memperbaiki error pada website Laravel, seperti route error, controller, validasi form, upload gambar, relasi database, dan tampilan Blade.</p><ol><li>Analisis error.</li><li>Perbaikan kode.</li><li>Testing hasil perbaikan.</li></ol>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Laravel, PHP, Debugging, MySQL',
                'whatsapp' => '081210010021',
                'email' => 'alvin@example.com',
            ],
            [
                'freelancer_name' => 'Hana Safitri',
                'service_name' => 'Penerjemah Dokumen Indonesia Inggris',
                'category' => 'Penerjemah',
                'price' => 180000,
                'location' => 'Bandung',
                'description' => '<p>Menerima jasa penerjemahan dokumen dari bahasa Indonesia ke Inggris maupun sebaliknya. Terjemahan dibuat dengan memperhatikan konteks, kejelasan makna, dan gaya bahasa yang sesuai.</p><p>Cocok untuk <strong>CV, abstrak, artikel, dan dokumen akademik ringan</strong>.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Translation, Proofreading, Academic Writing',
                'whatsapp' => '081210010022',
                'email' => 'hana.s@example.com',
            ],
            [
                'freelancer_name' => 'Rafi Alfarizi',
                'service_name' => 'Subtitle dan Translasi Video',
                'category' => 'Penerjemah',
                'price' => 250000,
                'location' => 'Surabaya',
                'description' => '<p>Jasa pembuatan subtitle dan terjemahan video untuk konten edukasi, promosi, webinar, dan media sosial. Subtitle dibuat sinkron, rapi, dan mudah dibaca.</p><ul><li>Subtitle Indonesia.</li><li>Subtitle Inggris.</li><li>Terjemahan sesuai konteks.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Subtitle, Translation, Video Captioning',
                'whatsapp' => '081210010023',
                'email' => 'rafi@example.com',
            ],
            [
                'freelancer_name' => 'Nabila Cahyani',
                'service_name' => 'Makeup Wisuda Soft Glam',
                'category' => 'Makeup Artist',
                'price' => 450000,
                'location' => 'Bekasi',
                'description' => '<p>Jasa makeup untuk wisuda dengan hasil <strong>soft glam</strong>, tahan lama, dan tetap terlihat natural. Makeup disesuaikan dengan bentuk wajah, warna kulit, dan gaya personal klien.</p><ol><li>Base makeup tahan lama.</li><li>Eye makeup rapi.</li><li>Finishing flawless.</li></ol>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Makeup, Hairdo, Soft Glam',
                'whatsapp' => '081210010024',
                'email' => 'nabila.c@example.com',
            ],
            [
                'freelancer_name' => 'Shafira Amalia',
                'service_name' => 'Makeup Wedding Natural Elegant',
                'category' => 'Makeup Artist',
                'price' => 900000,
                'location' => 'Medan',
                'description' => '<p>Menyediakan jasa makeup wedding dengan tampilan natural, elegan, dan <em>photogenic</em>. Riasan dibuat tahan lama untuk acara pagi hingga malam, namun tetap nyaman di wajah.</p><p>Termasuk konsultasi konsep makeup sesuai busana dan tema acara.</p>',
                'work_experience' => '6 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Wedding Makeup, Hair Styling, Hijab Styling',
                'whatsapp' => '081210010025',
                'email' => 'shafira@example.com',
            ],
            [
                'freelancer_name' => 'Farhan Akbar',
                'service_name' => 'Les Privat Matematika SMP SMA',
                'category' => 'Les Privat',
                'price' => 125000,
                'location' => 'Semarang',
                'description' => '<p>Les privat matematika untuk siswa SMP dan SMA dengan metode belajar bertahap dan mudah dipahami. Pembelajaran difokuskan pada pemahaman konsep, latihan soal, dan strategi mengerjakan ujian.</p><ul><li>Penjelasan materi.</li><li>Latihan soal.</li><li>Evaluasi progres belajar.</li></ul>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Matematika, Teaching, Problem Solving',
                'whatsapp' => '081210010026',
                'email' => 'farhan.a@example.com',
            ],
            [
                'freelancer_name' => 'Melani Kusuma',
                'service_name' => 'Les Bahasa Inggris Conversation',
                'category' => 'Les Privat',
                'price' => 140000,
                'location' => 'Palembang',
                'description' => '<p>Les privat bahasa Inggris untuk pelajar dan pemula dengan fokus pada <strong>conversation</strong>, grammar dasar, dan keberanian berbicara. Materi disesuaikan dengan kebutuhan siswa.</p><p>Pembelajaran dibuat santai, interaktif, dan tidak kaku.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'English Teaching, Speaking Practice, Grammar',
                'whatsapp' => '081210010027',
                'email' => 'melani@example.com',
            ],
            [
                'freelancer_name' => 'Gilang Wicaksana',
                'service_name' => 'Input Data dan Rekap Excel',
                'category' => 'Admin & Data Entry',
                'price' => 120000,
                'location' => 'Jakarta',
                'description' => '<p>Jasa input data, rekap Excel, pembersihan data sederhana, dan penyusunan tabel agar data lebih rapi. Cocok untuk kebutuhan administrasi, laporan, dan pengolahan data ringan.</p><ol><li>Input data manual.</li><li>Rekap tabel.</li><li>Format data agar lebih mudah dibaca.</li></ol>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Data Entry, Microsoft Excel, Google Sheets',
                'whatsapp' => '081210010028',
                'email' => 'gilang.w@example.com',
            ],
            [
                'freelancer_name' => 'Anisa Zahra',
                'service_name' => 'Virtual Assistant Administrasi',
                'category' => 'Admin & Data Entry',
                'price' => 250000,
                'location' => 'Bandung',
                'description' => '<p>Membantu pekerjaan administrasi online seperti mengelola dokumen, membuat jadwal, rekap data, dan follow up sederhana. Layanan ini cocok untuk pemilik bisnis yang membutuhkan bantuan administratif secara fleksibel.</p><p>Pekerjaan dilakukan secara <em>organized</em> dan komunikatif.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Virtual Assistant, Administration, Data Management',
                'whatsapp' => '081210010029',
                'email' => 'anisa.z@example.com',
            ],
            [
                'freelancer_name' => 'Vina Oktaviani',
                'service_name' => 'Admin Instagram dan TikTok UMKM',
                'category' => 'Social Media',
                'price' => 350000,
                'location' => 'Surabaya',
                'description' => '<p>Jasa pengelolaan akun Instagram dan TikTok untuk UMKM. Saya membantu membuat jadwal posting, menulis caption, merapikan ide konten, dan menjaga aktivitas akun tetap konsisten.</p><ul><li>Content scheduling.</li><li>Caption writing.</li><li>Basic engagement.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Social Media Admin, Caption Writing, Content Scheduling',
                'whatsapp' => '081210010030',
                'email' => 'vina.o@example.com',
            ],
            [
                'freelancer_name' => 'Reza Firmansyah',
                'service_name' => 'Strategi Konten Social Media',
                'category' => 'Social Media',
                'price' => 500000,
                'location' => 'Bekasi',
                'description' => '<p>Membantu menyusun strategi konten untuk Instagram, TikTok, dan media sosial bisnis. Strategi dibuat berdasarkan target audiens, karakter brand, dan tujuan promosi.</p><ol><li>Content pillar.</li><li>Ide konten bulanan.</li><li>Rekomendasi format posting.</li></ol>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Content Strategy, Social Media Planning, Branding',
                'whatsapp' => '081210010031',
                'email' => 'reza.f@example.com',
            ],
            [
                'freelancer_name' => 'Celine Andara',
                'service_name' => 'Foto Cafe dan Interior Bisnis',
                'category' => 'Fotografi',
                'price' => 600000,
                'location' => 'Semarang',
                'description' => '<p>Jasa fotografi interior untuk cafe, restoran, studio, dan ruang bisnis. Foto dibuat dengan memperhatikan cahaya, sudut ruangan, detail dekorasi, serta suasana tempat agar terlihat menarik.</p><p>Cocok untuk kebutuhan <strong>Google Business, Instagram, dan promosi digital</strong>.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Interior Photography, Lighting, Editing',
                'whatsapp' => '081210010032',
                'email' => 'celine@example.com',
            ],
            [
                'freelancer_name' => 'Reno Mahardika',
                'service_name' => 'Desain Katalog Produk Digital',
                'category' => 'Desain Grafis',
                'price' => 300000,
                'location' => 'Palembang',
                'description' => '<p>Membuat desain katalog produk digital untuk bisnis fashion, makanan, skincare, dan UMKM. Layout dibuat bersih, mudah dibaca, dan membantu calon pembeli memahami produk dengan cepat.</p><ul><li>Layout katalog.</li><li>Informasi produk rapi.</li><li>Desain sesuai identitas brand.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Catalogue Design, Canva, Layouting',
                'whatsapp' => '081210010033',
                'email' => 'reno@example.com',
            ],
            [
                'freelancer_name' => 'Yasmin Khairunnisa',
                'service_name' => 'Video Editing Edukasi Online',
                'category' => 'Video Editing',
                'price' => 280000,
                'location' => 'Medan',
                'description' => '<p>Jasa editing video edukasi untuk kelas online, materi pembelajaran, webinar, dan konten informatif. Video akan dibuat lebih rapi dengan tambahan teks, potongan yang tepat, dan audio yang lebih nyaman.</p><p>Hasil akhir disesuaikan dengan platform yang digunakan.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Educational Video, Subtitle, Editing',
                'whatsapp' => '081210010034',
                'email' => 'yasmin@example.com',
            ],
            [
                'freelancer_name' => 'Adit Nugraha',
                'service_name' => 'Audio Cleaning untuk Rekaman',
                'category' => 'Musik & Audio',
                'price' => 160000,
                'location' => 'Jakarta',
                'description' => '<p>Membantu membersihkan audio rekaman dari noise, suara angin, volume tidak stabil, dan gangguan kecil lainnya. Cocok untuk rekaman wawancara, podcast, kuliah, atau voice note penting.</p><ol><li>Noise reduction.</li><li>Volume balancing.</li><li>Export audio final.</li></ol>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Audio Cleaning, Noise Reduction, Editing',
                'whatsapp' => '081210010035',
                'email' => 'adit@example.com',
            ],
            [
                'freelancer_name' => 'Mikha Wijaya',
                'service_name' => 'Moderator Webinar dan Talkshow',
                'category' => 'MC & Event',
                'price' => 350000,
                'location' => 'Bandung',
                'description' => '<p>Jasa moderator untuk webinar, talkshow, diskusi publik, dan acara online. Saya membantu menjaga diskusi tetap terarah, komunikatif, dan nyaman diikuti peserta.</p><p>Gaya moderasi dapat dibuat formal, semi-formal, atau santai sesuai kebutuhan acara.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Moderating, Public Speaking, Webinar Handling',
                'whatsapp' => '081210010036',
                'email' => 'mikha@example.com',
            ],
            [
                'freelancer_name' => 'Raisa Damayanti',
                'service_name' => 'Proofreading Artikel dan Esai',
                'category' => 'Penulisan',
                'price' => 130000,
                'location' => 'Surabaya',
                'description' => '<p>Menyediakan jasa proofreading untuk artikel, esai, tugas kuliah, dan konten website. Saya membantu memperbaiki struktur kalimat, typo, alur tulisan, dan konsistensi gaya bahasa.</p><p>Hasil akhir dibuat lebih <strong>rapi, jelas, dan nyaman dibaca</strong>.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Proofreading, Editing, Academic Writing',
                'whatsapp' => '081210010037',
                'email' => 'raisa@example.com',
            ],
            [
                'freelancer_name' => 'Jonathan Lim',
                'service_name' => 'Website Portfolio Personal',
                'category' => 'Website & Programming',
                'price' => 750000,
                'location' => 'Bekasi',
                'description' => '<p>Jasa pembuatan website portfolio personal untuk freelancer, mahasiswa, content creator, dan profesional. Website dibuat responsif, modern, serta dapat menampilkan profil, karya, pengalaman, dan kontak.</p><ul><li>Desain halaman portfolio.</li><li>Responsive layout.</li><li>Link kontak dan media sosial.</li></ul>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Web Design, HTML, CSS, Laravel',
                'whatsapp' => '081210010038',
                'email' => 'jonathan@example.com',
            ],
            [
                'freelancer_name' => 'Dewi Larasati',
                'service_name' => 'Terjemah Abstrak dan Artikel Akademik',
                'category' => 'Penerjemah',
                'price' => 200000,
                'location' => 'Semarang',
                'description' => '<p>Jasa terjemah abstrak, artikel akademik ringan, dan dokumen pendidikan dari Indonesia ke Inggris atau sebaliknya. Terjemahan memperhatikan istilah, konteks, dan kelancaran bahasa.</p><p>Cocok untuk mahasiswa yang membutuhkan hasil terjemahan yang <em>clear</em> dan tidak kaku.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Academic Translation, Proofreading, Editing',
                'whatsapp' => '081210010039',
                'email' => 'dewi.l@example.com',
            ],
            [
                'freelancer_name' => 'Citra Ayuningtyas',
                'service_name' => 'Makeup Photoshoot dan Party Look',
                'category' => 'Makeup Artist',
                'price' => 500000,
                'location' => 'Palembang',
                'description' => '<p>Menyediakan makeup untuk photoshoot, party, dinner, dan acara semi-formal. Look dapat disesuaikan mulai dari natural, soft glam, hingga bold glam.</p><ol><li>Makeup sesuai request.</li><li>Base tahan lama.</li><li>Finishing camera-ready.</li></ol>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Party Makeup, Soft Glam, Photoshoot Makeup',
                'whatsapp' => '081210010040',
                'email' => 'citra.a@example.com',
            ],
        ];

        foreach ($services as $item) {
            $service = Service::create($item);

            for ($i = 1; $i <= 5; $i++) {
                ServiceImage::create([
                    'service_id' => $service->id,
                    'image' => 'service/portfolio/demo-' . $i . '.png',
                ]);
            }
        }
    }
}