<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceImage;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'freelancer_name' => 'Alya Putri',
                'service_name' => 'Fotografer Wisuda dan Event Kampus',
                'category' => 'Fotografi',
                'price' => 350000,
                'location' => 'Bandung',
                'description' => '<p>Jasa fotografi profesional untuk wisuda, event kampus, seminar, dan dokumentasi acara. Hasil foto akan diedit dengan tone modern, cerah, dan siap digunakan untuk media sosial maupun kebutuhan pribadi.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Fotografi, Editing Foto, Dokumentasi Event',
                'whatsapp' => '081234567890',
                'email' => 'alya@example.com',
            ],
            [
                'freelancer_name' => 'Raka Pratama',
                'service_name' => 'Fotografer Produk UMKM',
                'category' => 'Fotografi',
                'price' => 275000,
                'location' => 'Jakarta',
                'description' => '<p>Menyediakan jasa foto produk untuk katalog, marketplace, media sosial, dan promosi bisnis. Cocok untuk produk makanan, fashion, skincare, dan aksesoris.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Product Photography, Lighting, Editing Foto',
                'whatsapp' => '082112223333',
                'email' => 'raka@example.com',
            ],
            [
                'freelancer_name' => 'Nadia Safitri',
                'service_name' => 'Fotografer Prewedding Outdoor',
                'category' => 'Fotografi',
                'price' => 750000,
                'location' => 'Surabaya',
                'description' => '<p>Jasa fotografi prewedding dengan konsep outdoor yang natural, elegan, dan romantis. Termasuk arahan pose, editing warna, dan file digital resolusi tinggi.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Prewedding Photography, Photo Direction, Retouching',
                'whatsapp' => '083844556677',
                'email' => 'nadia@example.com',
            ],
            [
                'freelancer_name' => 'Dimas Mahendra',
                'service_name' => 'Desain Logo dan Identitas Brand',
                'category' => 'Desain Grafis',
                'price' => 250000,
                'location' => 'Medan',
                'description' => '<p>Membantu membuat logo, brand identity, dan kebutuhan visual bisnis agar terlihat profesional. Desain dibuat sesuai karakter brand dan target pasar.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Logo Design, Branding, Adobe Illustrator',
                'whatsapp' => '085677889900',
                'email' => 'dimas@example.com',
            ],
            [
                'freelancer_name' => 'Salsa Amalia',
                'service_name' => 'Desain Feed Instagram Bisnis',
                'category' => 'Desain Grafis',
                'price' => 180000,
                'location' => 'Palembang',
                'description' => '<p>Membuat desain feed Instagram yang rapi, modern, dan sesuai identitas brand. Cocok untuk UMKM, personal branding, dan promosi produk.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Canva, Social Media Design, Content Layout',
                'whatsapp' => '081998887777',
                'email' => 'salsa@example.com',
            ],
            [
                'freelancer_name' => 'Maya Lestari',
                'service_name' => 'Desain Poster dan Banner Event',
                'category' => 'Desain Grafis',
                'price' => 150000,
                'location' => 'Bandung',
                'description' => '<p>Jasa desain poster, banner, flyer, dan materi promosi event. Desain dibuat menarik, informatif, dan siap digunakan untuk cetak maupun digital.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Poster Design, Banner Design, Canva, Photoshop',
                'whatsapp' => '089912345678',
                'email' => 'maya@example.com',
            ],
            [
                'freelancer_name' => 'Fajar Ramadhan',
                'service_name' => 'Editor Video Reels dan TikTok',
                'category' => 'Video Editing',
                'price' => 150000,
                'location' => 'Jakarta',
                'description' => '<p>Jasa editing video pendek untuk Reels, TikTok, YouTube Shorts, dan konten promosi. Hasil video dibuat dinamis, rapi, dan mengikuti gaya konten saat ini.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'CapCut, Premiere Pro, Motion Graphic',
                'whatsapp' => '087711223344',
                'email' => 'fajar@example.com',
            ],
            [
                'freelancer_name' => 'Intan Maharani',
                'service_name' => 'Editor Video Dokumentasi Acara',
                'category' => 'Video Editing',
                'price' => 300000,
                'location' => 'Surabaya',
                'description' => '<p>Editing video dokumentasi acara, aftermovie, cinematic recap, dan video promosi. Cocok untuk seminar, wedding, gathering, dan event kampus.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Premiere Pro, Color Grading, Cinematic Editing',
                'whatsapp' => '086655443322',
                'email' => 'intan@example.com',
            ],
            [
                'freelancer_name' => 'Bagas Wicaksono',
                'service_name' => 'Editor Video Company Profile',
                'category' => 'Video Editing',
                'price' => 650000,
                'location' => 'Medan',
                'description' => '<p>Membantu proses editing video company profile, video promosi bisnis, dan konten presentasi perusahaan dengan hasil profesional dan komunikatif.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Video Editing, Storytelling, Motion Graphic',
                'whatsapp' => '081377665544',
                'email' => 'bagas@example.com',
            ],
            [
                'freelancer_name' => 'Laras Wulandari',
                'service_name' => 'Voice Over Talent Bahasa Indonesia',
                'category' => 'Musik & Audio',
                'price' => 175000,
                'location' => 'Palembang',
                'description' => '<p>Voice over untuk iklan, video pembelajaran, company profile, dan konten media sosial. Suara jelas, ramah, dan dapat disesuaikan dengan kebutuhan naskah.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Voice Over, Dubbing, Audio Recording',
                'whatsapp' => '088812349999',
                'email' => 'laras@example.com',
            ],
            [
                'freelancer_name' => 'Kevin Aditya',
                'service_name' => 'Mixing dan Mastering Audio Podcast',
                'category' => 'Musik & Audio',
                'price' => 200000,
                'location' => 'Bandung',
                'description' => '<p>Mengolah audio podcast, voice over, dan musik agar terdengar lebih jernih dan profesional. Noise akan dikurangi dan volume dibuat lebih seimbang.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Mixing, Mastering, Audio Editing',
                'whatsapp' => '082233445566',
                'email' => 'kevin@example.com',
            ],
            [
                'freelancer_name' => 'Citra Anjani',
                'service_name' => 'Jasa Jingle dan Musik Pendek',
                'category' => 'Musik & Audio',
                'price' => 350000,
                'location' => 'Jakarta',
                'description' => '<p>Membuat jingle, backsound pendek, dan musik sederhana untuk kebutuhan brand, iklan, podcast, maupun konten digital.</p>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Music Production, Jingle, Audio Arrangement',
                'whatsapp' => '081122334455',
                'email' => 'citra@example.com',
            ],
            [
                'freelancer_name' => 'Rani Febriani',
                'service_name' => 'MC Formal dan Event Kampus',
                'category' => 'MC & Event',
                'price' => 300000,
                'location' => 'Surabaya',
                'description' => '<p>MC untuk acara formal, seminar, workshop, gathering, dan event kampus. Pembawaan rapi, komunikatif, dan menyesuaikan konsep acara.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Public Speaking, Event Handling, MC Formal',
                'whatsapp' => '081234001122',
                'email' => 'rani@example.com',
            ],
            [
                'freelancer_name' => 'Ardi Nugroho',
                'service_name' => 'MC Wedding dan Engagement',
                'category' => 'MC & Event',
                'price' => 500000,
                'location' => 'Medan',
                'description' => '<p>MC untuk acara wedding, engagement, lamaran, gathering keluarga, dan event semi-formal. Alur acara dibawakan hangat dan tetap terstruktur.</p>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'MC Wedding, Public Speaking, Event Coordination',
                'whatsapp' => '082345667788',
                'email' => 'ardi@example.com',
            ],
            [
                'freelancer_name' => 'Tasya Kirana',
                'service_name' => 'Event Planner Mini Gathering',
                'category' => 'MC & Event',
                'price' => 450000,
                'location' => 'Palembang',
                'description' => '<p>Membantu merancang konsep acara kecil seperti gathering, ulang tahun, mini launching, dan acara komunitas agar lebih rapi dan terarah.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Event Planning, Rundown, Vendor Coordination',
                'whatsapp' => '083456778899',
                'email' => 'tasya@example.com',
            ],
            [
                'freelancer_name' => 'Putri Aisyah',
                'service_name' => 'Penulisan Artikel SEO Blog',
                'category' => 'Penulisan',
                'price' => 125000,
                'location' => 'Bandung',
                'description' => '<p>Jasa penulisan artikel SEO untuk blog, website bisnis, dan konten edukasi. Tulisan dibuat rapi, informatif, dan mudah dibaca.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'SEO Writing, Copywriting, Content Writing',
                'whatsapp' => '084567889900',
                'email' => 'putri@example.com',
            ],
            [
                'freelancer_name' => 'Yoga Saputra',
                'service_name' => 'Copywriting Produk dan Iklan',
                'category' => 'Penulisan',
                'price' => 175000,
                'location' => 'Jakarta',
                'description' => '<p>Membantu membuat copywriting untuk caption, landing page, katalog produk, dan iklan digital agar lebih menarik dan persuasif.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Copywriting, Marketing Content, Product Description',
                'whatsapp' => '085678990011',
                'email' => 'yoga@example.com',
            ],
            [
                'freelancer_name' => 'Dewi Anggraini',
                'service_name' => 'Penulisan CV dan LinkedIn Profile',
                'category' => 'Penulisan',
                'price' => 200000,
                'location' => 'Surabaya',
                'description' => '<p>Membantu menyusun CV profesional, profil LinkedIn, dan deskripsi pengalaman kerja agar lebih menarik untuk kebutuhan karier.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'CV Writing, Career Profile, LinkedIn Optimization',
                'whatsapp' => '086789001122',
                'email' => 'dewi@example.com',
            ],
            [
                'freelancer_name' => 'Andre Wijaya',
                'service_name' => 'Pembuatan Website Company Profile',
                'category' => 'Website & Programming',
                'price' => 1200000,
                'location' => 'Medan',
                'description' => '<p>Jasa pembuatan website company profile untuk bisnis, organisasi, dan personal branding. Website dibuat responsif, modern, dan mudah digunakan.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'HTML, CSS, Laravel, Web Design',
                'whatsapp' => '087890112233',
                'email' => 'andre@example.com',
            ],
            [
                'freelancer_name' => 'Monica Sari',
                'service_name' => 'Landing Page Produk dan UMKM',
                'category' => 'Website & Programming',
                'price' => 850000,
                'location' => 'Palembang',
                'description' => '<p>Membuat landing page untuk promosi produk, campaign, dan bisnis UMKM. Desain dibuat menarik dengan struktur yang mudah dipahami pengunjung.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Landing Page, Tailwind CSS, UI Design',
                'whatsapp' => '088901122334',
                'email' => 'monica@example.com',
            ],
            [
                'freelancer_name' => 'Rizky Maulana',
                'service_name' => 'Perbaikan Bug Website Laravel',
                'category' => 'Website & Programming',
                'price' => 300000,
                'location' => 'Bandung',
                'description' => '<p>Membantu memperbaiki bug website Laravel, error route, controller, form validation, upload file, dan tampilan Blade.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Laravel, PHP, Debugging, MySQL',
                'whatsapp' => '089012233445',
                'email' => 'rizky@example.com',
            ],
            [
                'freelancer_name' => 'Hana Prameswari',
                'service_name' => 'Penerjemah Dokumen Indonesia Inggris',
                'category' => 'Penerjemah',
                'price' => 150000,
                'location' => 'Jakarta',
                'description' => '<p>Jasa penerjemahan dokumen bahasa Indonesia ke Inggris atau sebaliknya. Cocok untuk artikel, CV, abstrak, dan dokumen akademik ringan.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Translation, Proofreading, Academic Writing',
                'whatsapp' => '081223344556',
                'email' => 'hana@example.com',
            ],
            [
                'freelancer_name' => 'Bima Prakoso',
                'service_name' => 'Subtitle dan Translasi Video',
                'category' => 'Penerjemah',
                'price' => 220000,
                'location' => 'Surabaya',
                'description' => '<p>Membantu membuat subtitle dan terjemahan video untuk kebutuhan konten edukasi, promosi, webinar, dan media sosial.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'Subtitle, Translation, Video Captioning',
                'whatsapp' => '082334455667',
                'email' => 'bima@example.com',
            ],
            [
                'freelancer_name' => 'Nabila Rahma',
                'service_name' => 'Makeup Artist Wisuda dan Photoshoot',
                'category' => 'Makeup Artist',
                'price' => 400000,
                'location' => 'Medan',
                'description' => '<p>Jasa makeup untuk wisuda, photoshoot, prewedding, dan acara formal. Tampilan makeup dibuat flawless, tahan lama, dan tetap natural.</p>',
                'work_experience' => '5 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Makeup, Hairdo, Hijab Styling',
                'whatsapp' => '083445566778',
                'email' => 'nabila@example.com',
            ],
            [
                'freelancer_name' => 'Shinta Maharani',
                'service_name' => 'Makeup Wedding Soft Glam',
                'category' => 'Makeup Artist',
                'price' => 850000,
                'location' => 'Palembang',
                'description' => '<p>Makeup wedding dengan konsep soft glam, elegan, dan photogenic. Cocok untuk pengantin yang ingin tampilan anggun namun tidak berlebihan.</p>',
                'work_experience' => '6 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Wedding Makeup, Soft Glam, Hair Styling',
                'whatsapp' => '084556677889',
                'email' => 'shinta@example.com',
            ],
            [
                'freelancer_name' => 'Farhan Hakim',
                'service_name' => 'Les Privat Matematika SMP SMA',
                'category' => 'Les Privat',
                'price' => 125000,
                'location' => 'Bandung',
                'description' => '<p>Les privat matematika untuk siswa SMP dan SMA dengan metode belajar yang bertahap, mudah dipahami, dan menyesuaikan kemampuan siswa.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Matematika, Teaching, Problem Solving',
                'whatsapp' => '085667788990',
                'email' => 'farhan@example.com',
            ],
            [
                'freelancer_name' => 'Melati Kusuma',
                'service_name' => 'Les Bahasa Inggris Conversation',
                'category' => 'Les Privat',
                'price' => 140000,
                'location' => 'Jakarta',
                'description' => '<p>Les privat bahasa Inggris dengan fokus conversation, grammar dasar, dan latihan berbicara untuk pelajar maupun pemula.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia', 'Inggris'],
                'skills' => 'English Teaching, Speaking Practice, Grammar',
                'whatsapp' => '086778899001',
                'email' => 'melati@example.com',
            ],
            [
                'freelancer_name' => 'Gilang Ramadhan',
                'service_name' => 'Input Data dan Rekap Excel',
                'category' => 'Admin & Data Entry',
                'price' => 100000,
                'location' => 'Surabaya',
                'description' => '<p>Jasa input data, rekap data Excel, pembersihan data sederhana, dan penyusunan tabel agar data lebih rapi dan mudah digunakan.</p>',
                'work_experience' => '2 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Data Entry, Microsoft Excel, Google Sheets',
                'whatsapp' => '087889900112',
                'email' => 'gilang@example.com',
            ],
            [
                'freelancer_name' => 'Anisa Zahra',
                'service_name' => 'Virtual Assistant Administrasi',
                'category' => 'Admin & Data Entry',
                'price' => 200000,
                'location' => 'Medan',
                'description' => '<p>Membantu pekerjaan administrasi online seperti membuat jadwal, mengelola dokumen, rekap data, dan follow up sederhana.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Virtual Assistant, Administration, Data Management',
                'whatsapp' => '088990011223',
                'email' => 'anisa@example.com',
            ],
            [
                'freelancer_name' => 'Vina Oktaviani',
                'service_name' => 'Admin Instagram dan TikTok UMKM',
                'category' => 'Social Media',
                'price' => 350000,
                'location' => 'Palembang',
                'description' => '<p>Jasa pengelolaan akun Instagram dan TikTok untuk UMKM, termasuk penjadwalan konten, caption, dan interaksi dasar dengan audiens.</p>',
                'work_experience' => '3 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Social Media Admin, Caption Writing, Content Scheduling',
                'whatsapp' => '089001122334',
                'email' => 'vina@example.com',
            ],
            [
                'freelancer_name' => 'Reza Firmansyah',
                'service_name' => 'Strategi Konten Social Media',
                'category' => 'Social Media',
                'price' => 450000,
                'location' => 'Bandung',
                'description' => '<p>Membantu menyusun strategi konten, content pillar, jadwal posting, dan ide konten untuk meningkatkan kualitas media sosial brand.</p>',
                'work_experience' => '4 Tahun',
                'languages' => ['Indonesia'],
                'skills' => 'Content Strategy, Social Media Planning, Branding',
                'whatsapp' => '081001122334',
                'email' => 'reza@example.com',
            ],
        ];

       foreach ($services as $item) {
            $item['languages'] = implode(', ', $item['languages']);

            $service = Service::updateOrCreate(
                ['email' => $item['email']], 
                $item
            );

            ServiceImage::where('service_id', $service->id)->delete();

            for ($i = 1; $i <= 5; $i++) {
                ServiceImage::create([
                    'service_id' => $service->id,
                    'image' => 'service/portfolio/demo-' . $i . '.png',
                ]);
            }
        }
    }
}